<?php
namespace service\member\constant;

/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * 基础状态
 */
final class BaseStatus {
  /**
   * 正常
   */
  const NORMAL = 1;
  /**
   * 删除
   */
  const DELETE = 2;
  /**
   * 已下架
   */
  const OFF_SHELF = 3;
  /**
   * 已归档
   */
  const ARCHIVE = 4;
  /**
   * 未知
   */
  const UNKNOWN_STATUS = 255;
  static public $__names = array(
    1 => 'NORMAL',
    2 => 'DELETE',
    3 => 'OFF_SHELF',
    4 => 'ARCHIVE',
    255 => 'UNKNOWN_STATUS',
  );
}

/**
 * 错误码
 */
final class ErrorCode {
  /**
   * 成功
   */
  const SUCCESS = 0;
  /**
   * 系统错误
   */
  const INTERNAL_ERROR = 10001;
  /**
   * 参数错误
   */
  const PARAMS_ERROR = 10002;
  /**
   * 数据服务请求失败
   */
  const DATA_SERVER_REQUEST_FAILED = 10003;
  /**
   * 数据接口不存在
   */
  const REQUEST_INTERFACE_NOT_EXIST = 10004;
  /**
   * 数据不存在
   */
  const DATA_NOT_FOUND = 10005;
  /**
   * 未知的数据来源类型
   */
  const DATA_SOURCE_UNKNOWN = 10006;
  static public $__names = array(
    0 => 'SUCCESS',
    10001 => 'INTERNAL_ERROR',
    10002 => 'PARAMS_ERROR',
    10003 => 'DATA_SERVER_REQUEST_FAILED',
    10004 => 'REQUEST_INTERFACE_NOT_EXIST',
    10005 => 'DATA_NOT_FOUND',
    10006 => 'DATA_SOURCE_UNKNOWN',
  );
}

/**
 * 返回数据的格式MAPPING
 */
final class DataByMappingTypeName {
  const BASE_FOR_LIST = 1;
  const BASE_FOR_VIEW = 2;
  static public $__names = array(
    1 => 'BASE_FOR_LIST',
    2 => 'BASE_FOR_VIEW',
  );
}

final class Constant extends \Thrift\Type\TConstant {
  static protected $ERROR_CODE_MESSAGE;
  static protected $DataByMappingTypeName;

  static protected function init_ERROR_CODE_MESSAGE() {
    return     /**
     * 错误信息
     */
array(
      0 => "成功",
      10001 => "系统错误",
      10002 => "参数错误",
      10003 => "数据服务请求失败",
      10004 => "请求的数据接口不存在",
      10005 => "数据不存在",
      10006 => "未知的数据来源类型",
    );
  }

  static protected function init_DataByMappingTypeName() {
    return array(
            1 => "BaseForList",
            2 => "BaseForView",
    );
  }
}


